root = "." # Es pacio de trabajo, se puede utilizar . o path absoluto
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main" # El binario que se genera por el CMD
  cmd = "make build_air" # Es el comando shell con el que corre tu aplicacion
  delay = 1000 # Es el tiempo de espera que le damos para recargar el proyecto
  exclude_dir = [] # Sirve para ignorar determinados extensiones o directorios
  exclude_file = [] # Sirve para ignorar determinados archivos
  exclude_regex = [] # Sirve para excluir por medio de REGEX
  exclude_unchanged = false # Sirve para excluir archivos sin cambios
  follow_symlink = false # Seguir enlaces simbolicos
  full_bin = "" # Sirve para personalizar el binario generado, tambien puede agregar variables de entorno
  include_dir = [] # Incluir un directorio para su escucha a cambios
  include_ext = ["go"] # Incluir determinadas extensiones para escuchar sus cambios
  kill_delay = "0s" # Retraso al matar el proceso
  log = "build-errors.log" # Archivo de log de error, se almacenan en tmp_dir
  send_interrupt = false # Enviar una señal antes de la interrupcion (Windows no es compatible)
  stop_on_error = true # Dejar de ejecutar el binario al tener errores

[color]
  # Sirve para personalizar cada parte con distintos colores 
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true # Sirve para loguear el tiempo en los logs de consola

[misc]
  clean_on_exit = true # Sirve para eliminar el tmp al salir del programa

[screen]
  clear_on_rebuild = true # Sirve para eliminar el tmp al rehacer build
